version: 2.1

orbs:
  maven: circleci/maven@0.0.12

workflows:
  maven_test:
    jobs:
      - maven/test # checkout, build, test, and upload test results


workflows:
  version: 2
  build-and-publish:
    jobs:
      - publish:   
          filters:
            branches:
              only: master


workflows:
   version: 2.1
   jobs:
      build:
         machine:
            java:
            version: 'oraclejdk8'
